<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BillMirror extends Model
{
    public $table = 'Cashier_BillMirror';

    protected $connection = 'sqlsrv';
    
    protected $primaryKey = 'id';

    public $incrementing = false;

    public $fillable = [
        'id',
        'BillNumber',
        'AccountNumber',
        'ServicePeriod',
        'AdditionalCharges',
        'Deductions',
        'NetAmount',
        'BillingDate',
        'ServiceDateFrom',
        'ServiceDateTo',
        'DueDate',
        'GenerationSystemCharge',
        'TransmissionDeliveryChargeKW',
        'TransmissionDeliveryChargeKWH',
        'SystemLossCharge',
        'DistributionDemandCharge',
        'DistributionSystemCharge',
        'SupplyRetailCustomerCharge',
        'SupplySystemCharge',
        'MeteringRetailCustomerCharge',
        'MeteringSystemCharge',
        'RFSC',
        'LifelineRate',
        'InterClassCrossSubsidyCharge',
        'PPARefund',
        'SeniorCitizenSubsidy',
        'MissionaryElectrificationCharge',
        'EnvironmentalCharge',
        'StrandedContractCosts',
        'NPCStrandedDebt',
        'FeedInTariffAllowance',
        'MissionaryElectrificationREDCI',
        'GenerationVAT',
        'TransmissionVAT',
        'SystemLossVAT',
        'DistributionVAT',
        'RealPropertyTax',
        'Notes',
        'UserId',
        'OtherGenerationRateAdjustment',
        'OtherTransmissionCostAdjustmentKW',
        'OtherTransmissionCostAdjustmentKWH',
        'OtherSystemLossCostAdjustment',
        'OtherLifelineRateCostAdjustment',
        'SeniorCitizenDiscountAndSubsidyAdjustment',
        'FranchiseTax',
        'BusinessTax',
        'AdjustmentType',
        'Form2307Amount',
        'DeductedDeposit',
        'ExcessDeposit',
        'IsUnlockedForPayment',
        'UnlockedBy',
        'Evat2Percent',
        'Evat5Percent',
        'AdjustmentNumber',
        'AdjustedBy',
        'DateAdjusted',
        'ForCancellation',
        'CancelRequestedBy',
        'CancelApprovedBy',
        'KatasNgVat',
        'SolarImportPresent',
        'SolarImportPrevious',
        'SolarExportPresent',
        'SolarExportPrevious',
        'SolarImportKwh',
        'SolarExportKwh',
        'GenerationChargeSolarExport',
        'SolarResidualCredit',
        'SolarDemandChargeKW',
        'SolarDemandChargeKWH',
        'SolarRetailCustomerCharge',
        'SolarSupplySystemCharge',
        'SolarMeteringRetailCharge',
        'SolarMeteringSystemCharge',
        'Item1',
        'Item2',
        'Item3',
        'Item4',
        'Item5',
        'PaidAmount',
        'Balance',
        'ACRM',
        'PowerActReduction',
        'ACRMVAT',
        'MissionaryElectrificationSPUG',
        'MissionaryElectrificationSPUGTRUEUP',
        'FranchiseTaxOthers',
        'OthersVAT',
        'AdvancedMaterialDeposit',
        'CustomerDeposit',
        'TransformerRental',
        'AdjustmentRequestedBy',
        'AdjustmentApprovedBy',
        'AdjustmentStatus',
        'DateAdjustmentRequested',
        'TermedPayments',
        'ORNumber',
        'ORDate',
        'BatchNumber',
        'Teller',
        'PaidBillId'
    ];

    protected $casts = [
        'id' => 'string',
        'BillNumber' => 'string',
        'AccountNumber' => 'string',
        'ServicePeriod' => 'date',
        'AdditionalCharges' => 'decimal:2',
        'Deductions' => 'decimal:2',
        'NetAmount' => 'decimal:2',
        'BillingDate' => 'date',
        'ServiceDateFrom' => 'date',
        'ServiceDateTo' => 'date',
        'DueDate' => 'date',
        'GenerationSystemCharge' => 'decimal:2',
        'TransmissionDeliveryChargeKW' => 'decimal:2',
        'TransmissionDeliveryChargeKWH' => 'decimal:2',
        'SystemLossCharge' => 'decimal:2',
        'DistributionDemandCharge' => 'decimal:2',
        'DistributionSystemCharge' => 'decimal:2',
        'SupplyRetailCustomerCharge' => 'decimal:2',
        'SupplySystemCharge' => 'decimal:2',
        'MeteringRetailCustomerCharge' => 'decimal:2',
        'MeteringSystemCharge' => 'decimal:2',
        'RFSC' => 'decimal:2',
        'LifelineRate' => 'decimal:2',
        'InterClassCrossSubsidyCharge' => 'decimal:2',
        'PPARefund' => 'decimal:2',
        'SeniorCitizenSubsidy' => 'decimal:2',
        'MissionaryElectrificationCharge' => 'decimal:2',
        'EnvironmentalCharge' => 'decimal:2',
        'StrandedContractCosts' => 'decimal:2',
        'NPCStrandedDebt' => 'decimal:2',
        'FeedInTariffAllowance' => 'decimal:2',
        'MissionaryElectrificationREDCI' => 'decimal:2',
        'GenerationVAT' => 'decimal:2',
        'TransmissionVAT' => 'decimal:2',
        'SystemLossVAT' => 'decimal:2',
        'DistributionVAT' => 'decimal:2',
        'RealPropertyTax' => 'decimal:2',
        'Notes' => 'string',
        'UserId' => 'string',
        'OtherGenerationRateAdjustment' => 'decimal:2',
        'OtherTransmissionCostAdjustmentKW' => 'decimal:2',
        'OtherTransmissionCostAdjustmentKWH' => 'decimal:2',
        'OtherSystemLossCostAdjustment' => 'decimal:2',
        'OtherLifelineRateCostAdjustment' => 'decimal:2',
        'SeniorCitizenDiscountAndSubsidyAdjustment' => 'decimal:2',
        'FranchiseTax' => 'decimal:2',
        'BusinessTax' => 'decimal:2',
        'AdjustmentType' => 'string',
        'Form2307Amount' => 'string',
        'DeductedDeposit' => 'decimal:2',
        'ExcessDeposit' => 'decimal:2',
        'IsUnlockedForPayment' => 'string',
        'UnlockedBy' => 'string',
        'Evat2Percent' => 'string',
        'Evat5Percent' => 'string',
        'AdjustmentNumber' => 'string',
        'AdjustedBy' => 'string',
        'DateAdjusted' => 'date',
        'ForCancellation' => 'string',
        'CancelRequestedBy' => 'string',
        'CancelApprovedBy' => 'string',
        'SolarImportPresent' => 'decimal:2',
        'SolarImportPrevious' => 'decimal:2',
        'SolarExportPresent' => 'decimal:2',
        'SolarExportPrevious' => 'decimal:2',
        'SolarImportKwh' => 'decimal:2',
        'SolarExportKwh' => 'decimal:2',
        'GenerationChargeSolarExport' => 'decimal:2',
        'SolarResidualCredit' => 'decimal:2',
        'SolarDemandChargeKW' => 'decimal:2',
        'SolarDemandChargeKWH' => 'decimal:2',
        'SolarRetailCustomerCharge' => 'decimal:2',
        'SolarSupplySystemCharge' => 'decimal:2',
        'SolarMeteringRetailCharge' => 'decimal:2',
        'SolarMeteringSystemCharge' => 'decimal:2',
        'Item1' => 'string',
        'Item2' => 'string',
        'Item3' => 'string',
        'Item4' => 'string',
        'Item5' => 'string',
        'PaidAmount' => 'decimal:2',
        'Balance' => 'decimal:2',
        'ACRM' => 'decimal:2',
        'PowerActReduction' => 'decimal:2',
        'ACRMVAT' => 'decimal:2',
        'MissionaryElectrificationSPUG' => 'decimal:2',
        'MissionaryElectrificationSPUGTRUEUP' => 'decimal:2',
        'FranchiseTaxOthers' => 'decimal:2',
        'OthersVAT' => 'decimal:2',
        'AdvancedMaterialDeposit' => 'decimal:2',
        'CustomerDeposit' => 'decimal:2',
        'TransformerRental' => 'decimal:2',
        'AdjustmentRequestedBy' => 'string',
        'AdjustmentApprovedBy' => 'string',
        'AdjustmentStatus' => 'string',
        'DateAdjustmentRequested' => 'datetime',
        'TermedPayments' => 'decimal:2',
        'ORNumber' => 'string',
        'ORDate' => 'date',
        'BatchNumber' => 'string',
        'Teller' => 'string',
        'PaidBillId' => 'string'
    ];

    public static array $rules = [
        'BillNumber' => 'nullable|string|max:255',
        'AccountNumber' => 'nullable|string|max:255',
        'ServicePeriod' => 'nullable',
        'AdditionalCharges' => 'nullable|numeric',
        'Deductions' => 'nullable|numeric',
        'NetAmount' => 'nullable|numeric',
        'BillingDate' => 'nullable',
        'ServiceDateFrom' => 'nullable',
        'ServiceDateTo' => 'nullable',
        'DueDate' => 'nullable',
        'GenerationSystemCharge' => 'nullable|numeric',
        'TransmissionDeliveryChargeKW' => 'nullable|numeric',
        'TransmissionDeliveryChargeKWH' => 'nullable|numeric',
        'SystemLossCharge' => 'nullable|numeric',
        'DistributionDemandCharge' => 'nullable|numeric',
        'DistributionSystemCharge' => 'nullable|numeric',
        'SupplyRetailCustomerCharge' => 'nullable|numeric',
        'SupplySystemCharge' => 'nullable|numeric',
        'MeteringRetailCustomerCharge' => 'nullable|numeric',
        'MeteringSystemCharge' => 'nullable|numeric',
        'RFSC' => 'nullable|numeric',
        'LifelineRate' => 'nullable|numeric',
        'InterClassCrossSubsidyCharge' => 'nullable|numeric',
        'PPARefund' => 'nullable|numeric',
        'SeniorCitizenSubsidy' => 'nullable|numeric',
        'MissionaryElectrificationCharge' => 'nullable|numeric',
        'EnvironmentalCharge' => 'nullable|numeric',
        'StrandedContractCosts' => 'nullable|numeric',
        'NPCStrandedDebt' => 'nullable|numeric',
        'FeedInTariffAllowance' => 'nullable|numeric',
        'MissionaryElectrificationREDCI' => 'nullable|numeric',
        'GenerationVAT' => 'nullable|numeric',
        'TransmissionVAT' => 'nullable|numeric',
        'SystemLossVAT' => 'nullable|numeric',
        'DistributionVAT' => 'nullable|numeric',
        'RealPropertyTax' => 'nullable|numeric',
        'Notes' => 'nullable|string|max:2500',
        'UserId' => 'nullable|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'OtherGenerationRateAdjustment' => 'nullable|numeric',
        'OtherTransmissionCostAdjustmentKW' => 'nullable|numeric',
        'OtherTransmissionCostAdjustmentKWH' => 'nullable|numeric',
        'OtherSystemLossCostAdjustment' => 'nullable|numeric',
        'OtherLifelineRateCostAdjustment' => 'nullable|numeric',
        'SeniorCitizenDiscountAndSubsidyAdjustment' => 'nullable|numeric',
        'FranchiseTax' => 'nullable|numeric',
        'BusinessTax' => 'nullable|numeric',
        'AdjustmentType' => 'nullable|string|max:50',
        'Form2307Amount' => 'nullable|string|max:50',
        'DeductedDeposit' => 'nullable|numeric',
        'ExcessDeposit' => 'nullable|numeric',
        'IsUnlockedForPayment' => 'nullable|string|max:50',
        'UnlockedBy' => 'nullable|string|max:50',
        'Evat2Percent' => 'nullable|string|max:50',
        'Evat5Percent' => 'nullable|string|max:50',
        'AdjustmentNumber' => 'nullable|string|max:80',
        'AdjustedBy' => 'nullable|string|max:50',
        'DateAdjusted' => 'nullable',
        'ForCancellation' => 'nullable|string|max:50',
        'CancelRequestedBy' => 'nullable|string|max:50',
        'CancelApprovedBy' => 'nullable|string|max:50',
        'KatasNgVat' => 'nullable',
        'SolarImportPresent' => 'nullable|numeric',
        'SolarImportPrevious' => 'nullable|numeric',
        'SolarExportPresent' => 'nullable|numeric',
        'SolarExportPrevious' => 'nullable|numeric',
        'SolarImportKwh' => 'nullable|numeric',
        'SolarExportKwh' => 'nullable|numeric',
        'GenerationChargeSolarExport' => 'nullable|numeric',
        'SolarResidualCredit' => 'nullable|numeric',
        'SolarDemandChargeKW' => 'nullable|numeric',
        'SolarDemandChargeKWH' => 'nullable|numeric',
        'SolarRetailCustomerCharge' => 'nullable|numeric',
        'SolarSupplySystemCharge' => 'nullable|numeric',
        'SolarMeteringRetailCharge' => 'nullable|numeric',
        'SolarMeteringSystemCharge' => 'nullable|numeric',
        'Item1' => 'nullable|string|max:50',
        'Item2' => 'nullable|string|max:255',
        'Item3' => 'nullable|string|max:100',
        'Item4' => 'nullable|string|max:50',
        'Item5' => 'nullable|string|max:50',
        'PaidAmount' => 'nullable|numeric',
        'Balance' => 'nullable|numeric',
        'ACRM' => 'nullable|numeric',
        'PowerActReduction' => 'nullable|numeric',
        'ACRMVAT' => 'nullable|numeric',
        'MissionaryElectrificationSPUG' => 'nullable|numeric',
        'MissionaryElectrificationSPUGTRUEUP' => 'nullable|numeric',
        'FranchiseTaxOthers' => 'nullable|numeric',
        'OthersVAT' => 'nullable|numeric',
        'AdvancedMaterialDeposit' => 'nullable|numeric',
        'CustomerDeposit' => 'nullable|numeric',
        'TransformerRental' => 'nullable|numeric',
        'AdjustmentRequestedBy' => 'nullable|string|max:50',
        'AdjustmentApprovedBy' => 'nullable|string|max:50',
        'AdjustmentStatus' => 'nullable|string|max:50',
        'DateAdjustmentRequested' => 'nullable',
        'TermedPayments' => 'nullable|numeric',
        'ORNumber' => 'nullable|string|max:50',
        'ORDate' => 'nullable',
        'BatchNumber' => 'nullable|string|max:90',
        'Teller' => 'nullable|string|max:50',
        'PaidBillId' => 'nullable|string|max:100'
    ];

    
}
